[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Chris Ling", email = "kurisuringu@gmail.com"},
]
dependencies = [
    "jupyterlab>=4.0.5",
    "pandas>=2.0.3",
    "seaborn>=0.12.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

